# docker-compose.yml for Code Live - The Ableton Live of Code
version: '3.8'

services:
  code-live:
    build: .
    container_name: code-live
    ports:
      - "8787:8787"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080,https://tunezilla-zz.github.io
    volumes:
      - ./site:/app/site:ro  # Serve static files
      - ./logs:/app/logs      # Persistent logs
      - ./data:/app/data      # Persistent data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - code-live-network

  # Optional: Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: code-live-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - code-live-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: code-live-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site:/usr/share/nginx/html:ro
    depends_on:
      - code-live
    restart: unless-stopped
    networks:
      - code-live-network

volumes:
  redis-data:

networks:
  code-live-network:
    driver: bridge
