name: Auto Labeler
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  auto-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
    - uses: actions/checkout@v4

    - name: Auto Labeler
      uses: actions/labeler@v4
      with:
        configuration-path: '.github/labeler.yml'
        sync-labels: true
